# Generated by Django 4.1.5 on 2023-01-03 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_rate_product_review_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='review_rate',
            field=models.FloatField(max_length=3),
        ),
    ]
